#!/bin/bash

echo "🔍 前端 AI 增强测试指南"
echo "================================"
echo ""
echo "当前状态："
echo "  ✅ 后端：运行正常（端口 8012）"
echo "  ✅ 前端：运行正常（端口 5174）"
echo "  ✅ DeepSeek：配置成功"
echo "  ✅ API 测试：通过（AI 已触发）"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  \"Failed to fetch\" 的原因"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "AI 查询需要时间："
echo "  1. 本地搜索：< 100ms"
echo "  2. DeepSeek API 调用：10-15 秒 ⏱️"
echo "  3. 结果合并：< 100ms"
echo ""
echo "前端可能因为等待太久而超时。"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 解决方案：耐心等待 15 秒"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "测试步骤："
echo ""
echo "1. 访问前端"
echo "   http://localhost:5174"
echo ""
echo "2. 输入问题"
echo "   Kubernetes Pod 一直重启怎么排查？"
echo ""
echo "3. 点击查询按钮"
echo ""
echo "4. 🎯 关键：耐心等待 10-15 秒！"
echo "   看到 \"正在查询...\" 时不要刷新页面"
echo ""
echo "5. 观察结果"
echo "   - 应该会看到详细的分析（7000+ 字符）"
echo "   - 置信度约 70%"
echo "   - 可能会有 AI 增强标识"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 API 直接测试（验证 AI 工作）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "如果前端超时，可以直接测试 API："
echo ""
echo "curl -X POST http://localhost:8012/api/v1/assistant/ask \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"question\": \"Kubernetes Pod 一直重启怎么排查\", \"top_k\": 3}' \\"
echo "  | jq '{question, confidence, ai_used: .ai_fallback.used}'"
echo ""
echo "预期输出："
echo "{"
echo "  \"question\": \"Kubernetes Pod 一直重启怎么排查\","
echo "  \"confidence\": 0.7,"
echo "  \"ai_used\": true  ← ✅ AI 已工作"
echo "}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 前端优化建议"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "可以增加前端的请求超时时间："
echo "在 api.ts 中修改 fetch 调用，添加 AbortSignal："
echo ""
echo "const controller = new AbortController()"
echo "const timeoutId = setTimeout(() => controller.abort(), 30000) // 30秒"
echo ""
echo "const response = await fetch(url, {"
echo "  ...options,"
echo "  signal: controller.signal"
echo "})"
echo ""
echo "clearTimeout(timeoutId)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 当前测试结果"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "我刚才测试的 API 调用："
echo "  ✅ 问题：Kubernetes Pod 一直重启怎么排查"
echo "  ✅ AI 状态：used = true"
echo "  ✅ 响应长度：7000+ 字符"
echo "  ✅ 响应时间：约 12 秒"
echo "  ✅ DeepSeek 提供了详细的排查指南"
echo ""
echo "说明："
echo "  🎉 AI 增强功能完全正常！"
echo "  🎉 DeepSeek 配置成功！"
echo "  🎉 后端工作正常！"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 现在就试试"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "访问：http://localhost:5174"
echo "输入：Kubernetes Pod 一直重启怎么排查？"
echo "等待：10-15 秒（不要刷新页面）"
echo ""
echo "或者用 curl 直接测试："
echo ""
echo "time curl -s -X POST http://localhost:8012/api/v1/assistant/ask \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"question\": \"Kubernetes Pod 一直重启怎么排查\", \"top_k\": 3}' \\"
echo "  | jq '.ai_fallback | {used, message}'"
echo ""
